### ISSUE TITLE
Implement email notifications

### ISSUE THREAD

**Issue by kirbyk** [USBlabs/Timecards#11]
- Create a sendgrid account.
- Implement sideqik as a background worker to check for timecards that haven't been submitted, and email accordingly.

Will also need to create the actual email templates.

**Comment by kirbyk** [comment]
@jay-hankins Status report?

**Comment by jay-hankins** [comment]
* Sendgrid account created :white_check_mark: 
* Sidekiq implemented... I made a rake task for this. Looks like we'll need to use Heroku's Scheduler in final implementation. :white_check_mark: 
* Cloned an email template off of GitHub. It's very basic but looks nice. The correct verbatim needs added. :white_check_mark:

**Comment by kirbyk** [comment]
Awesome.

**Comment by jay-hankins** [comment]
See #34.
