### ISSUE TITLE
Create basic reports view

### ISSUE THREAD

**Issue by kirbyk** [USBlabs/Timecards#15]
This will just display a user's cumulative time for the last 2 week period.

Buttons similar to #12 that don't work.

Dropdowns (that don't work):
- report range (this week, last week, this month, last month)
- report type (bar or list)

**Comment by kirbyk** [comment]
@jay-hankins you can still get started on this view even though everything you need isn't done.

**Comment by jay-hankins** [comment]
@kirbyk Yep, going to work on it tomorrow. Should this be its own model or just a controller? I can't figure out the best way to continue. @aloeb has /timecard/show and thought it would be best to put the basic view in there, but I was thinking of making a controller/view at /reports/basic which would pull from a specific timecard ID. Thoughts?

**Comment by kirbyk** [comment]
Yeah, you should probably make a whole controller for this, because that's where you'll want to put the "advanced" queries.

**Comment by jay-hankins** [comment]
Okay, in the latest commit I've got a skeleton for this. You can see it at `/reports/basic/:id`. 

I think it would be smart to rethink the layout/design of the timecard submission and view, mostly because having a 19-column table really isn't usable at all.

Anyway, I'm still having some trouble accessing the hours worked, but I'm working on it.

**Comment by kirbyk** [comment]
I'm sorry, which commit?

**Comment by kirbyk** [comment]
Yeah, we can fix that with some CSS. Wanna take a crack at it @nzetzl?

Maybe embed the input fields in some [bootstrap tables](http://getbootstrap.com/css/#tables)?

Obviously going to need to make the input fields less wide. Ping @balderfer for ideas.

**Comment by kirbyk** [comment]
@jay-hankins you basic report looks decent on my huge screen. Not sure what it looks like on a smaller one. Would also ask for @balderfer's input here too.

**Comment by jay-hankins** [comment]
Yeah, just some CSS clean up. Figured I'd leave it for people who said they preferred front end.
