### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by kirbyk** [USBlabs/Timecards#20]
Setup heroku and auto deploy from github

**Comment by kirbyk** [comment]
Status?

**Comment by Skwarte** [comment]
I am having trouble pushing this to master. When I tried two weeks ago it said that it was successfully deployed (it also shows up on the heroku site, also) so I assumed that it was up and working but I'm not all too sure.

**Comment by kirbyk** [comment]
Can you pull master and push to heroku now?

**Comment by Skwarte** [comment]
Heroku is now deployed successfully (again), this issue can be closed now
