### ISSUE TITLE
Handle timecard submission

### ISSUE THREAD

**Issue by kirbyk** [USBlabs/Timecards#23]
Change status
Send email confirmation to supervisor (if not already implemented)

**Comment by kirbyk** [comment]
@nzetzl talk to @jay-hankins about how to do this.

**Comment by aloeb** [comment]
Also @nzetzl , if you need helping understanding the timecard model let me know. Because it works closely with a couple other models that need to do stuff when you submit a timecard.

**Comment by nzetzl** [comment]
@aloeb Yea that would probably help a lot. Are you free anytime tomorrow (Monday)?

**Comment by aloeb** [comment]
@nzetzl I can meet at 2:30 in Lawson Commons. That'll give us some time before we meet to talk it over.

**Comment by nzetzl** [comment]
Alright sounds good

**Comment by aloeb** [comment]
See #48 for submitting to database
