### ISSUE TITLE
README

### ISSUE THREAD

**Issue by kirbyk** [USBlabs/Timecards#37]
@jay-hankins you've recently added some stuff (sidekiq) that makes running our app slightly more complex. Can you remove all the default crap in the README and make it have the following:
- How to clone the repo
- How to migrate and bundle
- How to run the server
- How to run sideqik
- Talk about env variables and stuff

Also, if you could make the README markdown instead of rdoc, that would be fantastic.

Thank you!!

**Comment by jay-hankins** [comment]
Yep, I can try. Don't look for it before 3:59 PM tomorrow though.

Can I get clarification on:
- How to migrate and bundle
- Env variables (how should we share them if not on GitHub?)

**Comment by kirbyk** [comment]
Lol, okay.

Just running `rake db:migrate` and how you might have to run `rake db:drop` and how to `bundle install`.

List all the variables we have, how to create them. We'll share them via email.
