### ISSUE TITLE
Create Job Scaffold

### ISSUE THREAD

**Issue by kirbyk** [USBlabs/Timecards#4]
A job with have these attributes:
- name
- user_id (for the advisor)
- cost_center_id
- wbse_id
- fund_id
- order_id

**Comment by cpund** [comment]
Sorry I got around to this so late. Is this looking alright, or did I go about it wrong? @kirbyk

**Comment by kirbyk** [comment]
I'm really confused by what you did. First off, you need to make a PR over [here](https://github.com/USBlabs/Timecards/branches) so that we can comment on your actual changes.

Also, I only see one commit on your branch, which is fine, but that commit doesn't add a `Job` controller, model, or view.

You should have just had to run something like `rails g scaffold job name:string user_id:integer ...` which would have autogenerated all the files.

**Comment by cpund** [comment]
I used rails g scaffold Job name:string ...  But, I didn't do a pull request. I just cloned the repo. Perhaps that is the reason why? When I go back to my room in an hour I'll fix that and do a PR. Should I create a new branch, or erase this current one?

**Comment by kirbyk** [comment]
If your local branch has commits with the stuff I was takling about, then just push it and PR it.

If not, create a new branch, delete the old, and PR the new.

**Comment by cpund** [comment]
Implemented in #32, closing. :closed_book:
